version: '2'

services:

  app:
    build:
      context: ./build/app
      dockerfile: ${app_dockerfile}
    depends_on:
      - db
    environment:
      - MYSQL_HOST=${app_mysql_host}
      - MYSQL_USER=${db_user}
      - MYSQL_PASSWORD=${db_password}
      - MYSQL_DATABASE=${db_name}
      - ALLOW_EXPORT="${app_allow_export}"
      - ALLOW_IMPORT="${app_allow_import}"
      - ALLOW_PERSONAL_PASSWORDS="${app_personal_passwords}"
    volumes:
      - ./config/app/config.php:/var/www/app/config.template
      - ./data/app/:/var/www/app/
    ports:
      - 9000

  db:
    image: mariadb:10
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${db_root_password}
      - MYSQL_DATABASE=${db_name}
      - MYSQL_USER=${db_user}
      - MYSQL_PASSWORD=${db_password}

  proxy:
    build:
      context: ./build/proxy
      dockerfile: ${proxy_dockerfile}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf.template
      - ./data/proxy/lets-etc/:/etc/letsencrypt/
      - ./data/proxy/lets-var-lib/:/var/lib/letsencrypt/
      - ./data/proxy/nginx-root/:/usr/share/nginx/html/
    environment:
      - VIRTUAL_HOST=${proxy_domain}
      - ADMIN_EMAIL=${proxy_admin_email}
      - DOMAIN=${proxy_domain}
