version: '2'

services:

  app:
    build:
      context: ./build/app
      dockerfile: ${app_dockerfile}
    environment:
      - MYSQL_HOST=${app_db_host}
      - MYSQL_USER=${db_user}
      - MYSQL_PASSWORD=${db_password}
      - MYSQL_DATABASE=${db_name}
      - ALLOW_EXPORT="${app_allow_export}"
      - ALLOW_IMPORT="${app_allow_import}"
      - ALLOW_PERSONAL_PASSWORDS="${app_personal_passwords}"
    volumes:
      - ./config/app/config.php:/var/www/app/config.template
      - ./data/app/:/var/www/app/
    ports:
      - 9000

  proxy:
    build:
      context: ./build/proxy
      dockerfile: ${proxy_dockerfile}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf.template
    environment:
      - DOMAIN=${proxy_domain}
    networks:
      - default
      - ambassador

networks:
  default:
  ambassador:
    external:
      name: ambassador
